Feature/weather app
damiecode/Weather-App pull request #1
Opened 2020-02-18 00:18 UTC by damiecode

Thank you for taking the time to review my project. 
Work-done

- [x] Setup project using npm and add WebPack dependencies 
- [x]  Setup Api call from OpenWeather using async/await
- [x] Make sure temperature can be converted from Fahrenheit to Celcius and vis-a-vis

2020-02-18 06:57 UTC, Oghenebrume50 requested changes
### STATUS: CHANGES REQUIRED 

Hi @damiecode good job on this implementation it really looks clean!! :+1: there are just a few changes to make and some additions as outlined below :slightly_smiling_face: 

- The background should change for every search ![see this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png)

- When a wrong location is entered please remove previously searched information

Please make changes and request for another review :slightly_smiling_face: 

**RAPHAEL NORIODE** :sunglasses:

2020-02-18 06:57 UTC, Oghenebrume50 commented on src/index.js
> +    img.alt = data.list[0].weather[0].description;
Use Es6 destructing to get data from these objects ![see this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/destructuring_requirement.png)

2020-02-18 06:57 UTC, Oghenebrume50 commented on src/index.js
> +  await displayWeather(weatherJSON);
You do not really need to await this function call, it would be called along side the api call without the await

2020-02-18 06:57 UTC, Oghenebrume50 commented on src/index.js
> +const convertTemperature = () => {
Make an API  call for both Celsius and Fahrenheit ![see this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/requests_requirement.png)

2020-02-18 06:57 UTC, Oghenebrume50 commented on src/index.js
> +  const weatherJSON = await response.json();
There is no error handling for this ![see this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/error_handling_requirement.png)

2020-02-19 20:18 UTC, shloch approved these changes
![accomplished](https://user-images.githubusercontent.com/40712459/74872344-574dc580-535d-11ea-83ac-390cc23d14d2.jpg)

NICE JOB WITH CHANGES @damiecode 
We are good to go

2020-02-19 20:31 UTC, merged